[package]
name = "mei-host-auth"
version = "2.0.5"
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
argon2 = "0.5"
axum.workspace = true
base64 = "0.22"
chrono = "0.4.44"
clap.workspace = true
jsonwebtoken = "9.3"
mei-lang-app = { path = "../../app" }
mei-lang-kernel = { path = "../kernel" }
rand = "0.8"
rsa = { version = "0.9", features = ["pem"] }
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10"
tracing.workspace = true

[dev-dependencies]
tempfile = "3"
tower = { version = "0.5", features = ["util"] }
