[package]
name = "mei-plug-ds"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "mei-plug-ds"
path = "src/bin/main.rs"

[dependencies]
anyhow.workspace = true
axum.workspace = true
clap.workspace = true
mei-host-core = { path = "../mei-host-core" }
mei-host-graph = { path = "../mei-host-graph" }
mei-lang-datasets = { path = "../datasets" }
mei-lang-kernel = { path = "../kernel" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
http-body-util = "0.1"
tempfile = "3"
tower = { version = "0.5", features = ["util"] }
