use super::types::*;

pub(super) fn author_assets() -> Vec<AssetSeed> {
    vec![
        AssetSeed {
            id: "meilang_author_skill",
            topic: "workflow",
            kind: "skill_entry",
            title: "MeiLang Author Skill",
            rel_path: "guides/author-skills/SKILL.md",
            install_rel_path: "runtime/platform/skills/meilang-author/SKILL.md",
            summary: "Authoring entrypoint for external AI tools.",
            injection_roles: &["system", "workflow"],
        },
        AssetSeed {
            id: "author_profile",
            topic: "profile",
            kind: "profile",
            title: "Author Profile",
            rel_path: "guides/author-profile.md",
            install_rel_path: "runtime/platform/profiles/author.md",
            summary: "Canonical source-first authoring profile for packaged runtime consumers.",
            injection_roles: &["system", "profile"],
        },
        AssetSeed {
            id: "authoring",
            topic: "workflow",
            kind: "guide",
            title: "Authoring Guide",
            rel_path: "guides/author-skills/authoring.md",
            install_rel_path: "runtime/platform/skills/meilang-author/authoring.md",
            summary: "Source-first authoring workflow and editing boundaries.",
            injection_roles: &["workflow", "repair"],
        },
        AssetSeed {
            id: "syntax_rules",
            topic: "syntax",
            kind: "reference",
            title: "Syntax Rules",
            rel_path: "guides/author-skills/syntax-rules.md",
            install_rel_path: "runtime/platform/skills/meilang-author/syntax-rules.md",
            summary: "Stable MeiLang syntax and current authoring boundaries.",
            injection_roles: &["syntax", "validation"],
        },
        AssetSeed {
            id: "dsl_reference",
            topic: "syntax",
            kind: "reference",
            title: "DSL Reference",
            rel_path: "guides/author-skills/dsl-reference.md",
            install_rel_path: "runtime/platform/skills/meilang-author/dsl-reference.md",
            summary: "Current app, scene, dataset, chart, and template authoring skeletons.",
            injection_roles: &["syntax", "examples"],
        },
        AssetSeed {
            id: "namespace_reference",
            topic: "syntax",
            kind: "reference",
            title: "Namespace Reference",
            rel_path: "guides/author-skills/namespace-reference.md",
            install_rel_path: "runtime/platform/skills/meilang-author/namespace-reference.md",
            summary: "Current public helper names, typed refs, and compat boundaries.",
            injection_roles: &["syntax", "names"],
        },
        AssetSeed {
            id: "components_reference",
            topic: "components",
            kind: "reference",
            title: "Components Reference",
            rel_path: "guides/author-skills/components-reference.md",
            install_rel_path: "runtime/platform/skills/meilang-author/components-reference.md",
            summary: "Known component ids and usage patterns.",
            injection_roles: &["components", "completion"],
        },
        AssetSeed {
            id: "component_contracts",
            topic: "components",
            kind: "contract",
            title: "Component Contracts",
            rel_path: "knowledge/editor-runtime/components/component-contracts.json",
            install_rel_path: "runtime/platform/knowledge/author/components/component-contracts.json",
            summary: "Machine-readable public component contract index for standalone authoring.",
            injection_roles: &["components", "contracts"],
        },
        AssetSeed {
            id: "dataset_components_guide",
            topic: "components",
            kind: "guide",
            title: "Dataset Components Guide",
            rel_path: "knowledge/editor-runtime/components/dataset-components.md",
            install_rel_path: "runtime/platform/knowledge/author/components/dataset-components.md",
            summary: "Standalone-friendly public guide for dataset table/filter/summary components.",
            injection_roles: &["components", "recipes"],
        },
        AssetSeed {
            id: "chart_components_guide",
            topic: "components",
            kind: "guide",
            title: "Chart Components Guide",
            rel_path: "knowledge/editor-runtime/components/chart-components.md",
            install_rel_path: "runtime/platform/knowledge/author/components/chart-components.md",
            summary: "Standalone-friendly public guide for chart.* components and mapping usage.",
            injection_roles: &["components", "recipes"],
        },
        AssetSeed {
            id: "cockpit_components_guide",
            topic: "components",
            kind: "guide",
            title: "Cockpit Components Guide",
            rel_path: "knowledge/editor-runtime/components/cockpit-components.md",
            install_rel_path: "runtime/platform/knowledge/author/components/cockpit-components.md",
            summary: "Standalone-friendly public guide for cockpit renderer components.",
            injection_roles: &["components", "recipes"],
        },
        AssetSeed {
            id: "author_context",
            topic: "context",
            kind: "guide",
            title: "Author Context",
            rel_path: "guides/author-skills/context.md",
            install_rel_path: "runtime/platform/skills/meilang-author/context.md",
            summary: "Reading order and contextual authoring hints.",
            injection_roles: &["workflow", "context"],
        },
        AssetSeed {
            id: "author_runtime_overview",
            topic: "bootstrap",
            kind: "guide",
            title: "Author Runtime Overview",
            rel_path: "knowledge/editor-runtime/authoring-overview.md",
            install_rel_path: "runtime/platform/knowledge/author/authoring-overview.md",
            summary: "Standalone author runtime overview for external tools.",
            injection_roles: &["system", "bootstrap"],
        },
        AssetSeed {
            id: "language_and_editor_recognition",
            topic: "editor",
            kind: "guide",
            title: "Language And Editor Recognition",
            rel_path: "knowledge/editor-runtime/language-and-editor-recognition.md",
            install_rel_path: "runtime/platform/knowledge/author/language-and-editor-recognition.md",
            summary: "How to register language id mei, install mei-lang-vscode, and wire mei-lsp in Cursor/VS Code.",
            injection_roles: &["system", "editor", "bootstrap"],
        },
        AssetSeed {
            id: "workspace_config_reference",
            topic: "config",
            kind: "guide",
            title: "Workspace Config Reference",
            rel_path: "knowledge/editor-runtime/workspace-config-reference.md",
            install_rel_path: "runtime/platform/knowledge/author/workspace-config-reference.md",
            summary: "Standalone guide for workspace bootstrap, create-app, config layering, upload sources, and theme selection.",
            injection_roles: &["bootstrap", "config"],
        },
        AssetSeed {
            id: "workflow_recipes",
            topic: "workflow",
            kind: "guide",
            title: "Workflow Recipes",
            rel_path: "knowledge/editor-runtime/workflow-recipes.md",
            install_rel_path: "runtime/platform/knowledge/author/workflow-recipes.md",
            summary: "Recommended authoring recipes for external IDE and agent tools.",
            injection_roles: &["workflow", "recipes"],
        },
        AssetSeed {
            id: "build_debug_ops",
            topic: "ops",
            kind: "guide",
            title: "Build And Debug Ops",
            rel_path: "knowledge/editor-runtime/build-debug-ops.md",
            install_rel_path: "runtime/platform/knowledge/author/build-debug-ops.md",
            summary: "Build, debug, materialize, and doctor command recipes.",
            injection_roles: &["ops", "debug"],
        },
        AssetSeed {
            id: "cockpit_template_index",
            topic: "templates",
            kind: "guide",
            title: "Cockpit Template Index",
            rel_path: "knowledge/editor-runtime/templates/cockpit-template-index.md",
            install_rel_path: "runtime/platform/knowledge/author/templates/cockpit-template-index.md",
            summary: "Standalone-friendly public guide for cockpit template shells and paths.",
            injection_roles: &["templates", "recipes"],
        },
        AssetSeed {
            id: "template_contracts",
            topic: "templates",
            kind: "contract",
            title: "Template Contracts",
            rel_path: "knowledge/editor-runtime/templates/template-contracts.json",
            install_rel_path: "runtime/platform/knowledge/author/templates/template-contracts.json",
            summary: "Machine-readable public template contract index for standalone authoring.",
            injection_roles: &["templates", "contracts"],
        },
        AssetSeed {
            id: "dsl_contracts",
            topic: "syntax",
            kind: "contract",
            title: "DSL Contracts",
            rel_path: "knowledge/editor-runtime/syntax/dsl-contracts.json",
            install_rel_path: "runtime/platform/knowledge/author/syntax/dsl-contracts.json",
            summary: "Machine-readable contract index for the current public DSL and config refs.",
            injection_roles: &["syntax", "contracts"],
        },
        AssetSeed {
            id: "author_example_pack",
            topic: "examples",
            kind: "guide",
            title: "Author Example Pack",
            rel_path: "knowledge/editor-runtime/examples/README.md",
            install_rel_path: "runtime/platform/knowledge/author/examples/README.md",
            summary: "Curated standalone authoring example pack with proof points per contract.",
            injection_roles: &["examples", "index"],
        },
        AssetSeed {
            id: "standalone_minimal_app",
            topic: "examples",
            kind: "example",
            title: "Standalone Minimal App",
            rel_path: "knowledge/editor-runtime/minimal-app-main.mei",
            install_rel_path: "runtime/platform/knowledge/author/minimal-app-main.mei",
            summary: "Minimal standalone MeiLang app entrypoint shipped with the author runtime bundle.",
            injection_roles: &["examples", "bootstrap"],
        },
        AssetSeed {
            id: "standalone_minimal_scene",
            topic: "examples",
            kind: "example",
            title: "Standalone Minimal Home Scene",
            rel_path: "knowledge/editor-runtime/minimal-app-home.mei",
            install_rel_path: "runtime/platform/knowledge/author/minimal-app-home.mei",
            summary: "Minimal standalone MeiLang scene file shipped with the author runtime bundle.",
            injection_roles: &["examples", "bootstrap"],
        },
        AssetSeed {
            id: "example_dataset_baseline",
            topic: "examples",
            kind: "example",
            title: "Dataset Baseline Example",
            rel_path: "knowledge/editor-runtime/examples/dataset-baseline.mei",
            install_rel_path: "runtime/platform/knowledge/author/examples/dataset-baseline.mei",
            summary: "Minimal dataset/table/summary example for standalone authoring.",
            injection_roles: &["examples", "components"],
        },
        AssetSeed {
            id: "example_filter_reactivity",
            topic: "examples",
            kind: "example",
            title: "Filter Reactivity Example",
            rel_path: "knowledge/editor-runtime/examples/filter-reactivity.mei",
            install_rel_path: "runtime/platform/knowledge/author/examples/filter-reactivity.mei",
            summary: "Example proving dataset.filter-bar and shared query_state reactivity.",
            injection_roles: &["examples", "workflow"],
        },
        AssetSeed {
            id: "example_chart_baseline",
            topic: "examples",
            kind: "example",
            title: "Chart Baseline Example",
            rel_path: "knowledge/editor-runtime/examples/chart-baseline.mei",
            install_rel_path: "runtime/platform/knowledge/author/examples/chart-baseline.mei",
            summary: "Minimal chart example proving the common chart data+mapping contract.",
            injection_roles: &["examples", "components"],
        },
        AssetSeed {
            id: "example_data_table_runtime",
            topic: "examples",
            kind: "example",
            title: "Cockpit Data Table Runtime Example",
            rel_path: "knowledge/editor-runtime/examples/data-table-runtime.mei",
            install_rel_path: "runtime/platform/knowledge/author/examples/data-table-runtime.mei",
            summary: "Example proving cockpit.data-table public props on top of the shared table runtime.",
            injection_roles: &["examples", "components"],
        },
        AssetSeed {
            id: "example_cockpit_panel",
            topic: "examples",
            kind: "example",
            title: "Cockpit Panel Example",
            rel_path: "knowledge/editor-runtime/examples/cockpit-panel.mei",
            install_rel_path: "runtime/platform/knowledge/author/examples/cockpit-panel.mei",
            summary: "Example proving cockpit shell reuse via panel_ref template cloning.",
            injection_roles: &["examples", "templates"],
        },
        AssetSeed {
            id: "example_template_clone",
            topic: "examples",
            kind: "example",
            title: "Template Clone Example",
            rel_path: "knowledge/editor-runtime/examples/template-clone.mei",
            install_rel_path: "runtime/platform/knowledge/author/examples/template-clone.mei",
            summary: "Example proving metric_card template clone via metric_card_ref.",
            injection_roles: &["examples", "templates"],
        },
        AssetSeed {
            id: "example_multi_scene_app",
            topic: "examples",
            kind: "example",
            title: "Multi Scene App Example",
            rel_path: "knowledge/editor-runtime/examples/multi-scene-app.mei",
            install_rel_path: "runtime/platform/knowledge/author/examples/multi-scene-app.mei",
            summary: "App root example proving multi-file scene registration through app_add_scene(scene_ref(...)).",
            injection_roles: &["examples", "workflow"],
        },
        AssetSeed {
            id: "example_multi_scene_home",
            topic: "examples",
            kind: "example",
            title: "Multi Scene Home Support Example",
            rel_path: "knowledge/editor-runtime/examples/multi-scene-home.mei",
            install_rel_path: "runtime/platform/knowledge/author/examples/multi-scene-home.mei",
            summary: "Support scene file for the public multi-scene app skeleton.",
            injection_roles: &["examples", "workflow"],
        },
        AssetSeed {
            id: "example_multi_scene_insights",
            topic: "examples",
            kind: "example",
            title: "Multi Scene Insights Support Example",
            rel_path: "knowledge/editor-runtime/examples/multi-scene-insights.mei",
            install_rel_path: "runtime/platform/knowledge/author/examples/multi-scene-insights.mei",
            summary: "Second support scene file for the public multi-scene app skeleton.",
            injection_roles: &["examples", "workflow"],
        },
        AssetSeed {
            id: "example_frame_layout_advanced",
            topic: "examples",
            kind: "example",
            title: "Frame Layout Advanced Example",
            rel_path: "knowledge/editor-runtime/examples/frame-layout-advanced.mei",
            install_rel_path: "runtime/platform/knowledge/author/examples/frame-layout-advanced.mei",
            summary: "Example proving nested panel.blocks plus cockpit shell composition.",
            injection_roles: &["examples", "templates"],
        },
        AssetSeed {
            id: "example_metric_page_baseline",
            topic: "examples",
            kind: "example",
            title: "Metric Page Baseline Example",
            rel_path: "knowledge/editor-runtime/examples/metric-page-baseline.mei",
            install_rel_path: "runtime/platform/knowledge/author/examples/metric-page-baseline.mei",
            summary: "Metric-centric page example combining world.add_metric, summary cards, chart, and table.",
            injection_roles: &["examples", "workflow"],
        },
        AssetSeed {
            id: "example_upload_dataset_baseline",
            topic: "examples",
            kind: "example",
            title: "Upload Dataset Baseline Example",
            rel_path: "knowledge/editor-runtime/examples/upload-dataset-baseline.mei",
            install_rel_path: "runtime/platform/knowledge/author/examples/upload-dataset-baseline.mei",
            summary: "Example proving upload-backed dataset binding through source_ref(...) and app-local ops.sources.",
            injection_roles: &["examples", "config"],
        },
        AssetSeed {
            id: "example_sim_baseline",
            topic: "examples",
            kind: "example",
            title: "Sim Baseline Example",
            rel_path: "knowledge/editor-runtime/examples/sim-baseline.mei",
            install_rel_path: "runtime/platform/knowledge/author/examples/sim-baseline.mei",
            summary: "Minimal sim.scene example for standalone authoring.",
            injection_roles: &["examples", "components"],
        },
        AssetSeed {
            id: "example_map_baseline",
            topic: "examples",
            kind: "example",
            title: "Map Baseline Example",
            rel_path: "knowledge/editor-runtime/examples/map-baseline.mei",
            install_rel_path: "runtime/platform/knowledge/author/examples/map-baseline.mei",
            summary: "Minimal map.maplibre example proving the public mapSpec contract.",
            injection_roles: &["examples", "components"],
        },
        AssetSeed {
            id: "extension_authoring",
            topic: "extension",
            kind: "guide",
            title: "Extension Authoring Boundary",
            rel_path: "knowledge/editor-runtime/extension-authoring.md",
            install_rel_path: "runtime/platform/knowledge/author/extension-authoring.md",
            summary: "Boundary guide for tasks that leave normal MeiLang authoring and enter extension work.",
            injection_roles: &["workflow", "boundaries"],
        },
    ]
}
