[package]
name = "ws-spbjw-integration-tests"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
mei-lang-app = { path = "../../host-shell/app" }
mei-lang-datasets = { path = "../datasets" }
mei-lang-kernel = { path = "../kernel" }
serde_json.workspace = true

[dev-dependencies]
mei-lang-server = { path = "../../server" }
