[package]
name = "mei-host-graph"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
mei-bundle = { path = "../../mei-compiler/crates/mei-bundle" }
mei-graph = { path = "../../mei-compiler/crates/mei-graph" }
mei-syntax = { path = "../../mei-compiler/crates/mei-syntax" }
mei-host-core = { path = "../mei-host-core" }
mei-lang-kernel = { path = "../kernel" }
mei-lang-datasets = { path = "../datasets" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
walkdir.workspace = true

[dev-dependencies]
tempfile = "3"
mei-lang-datasets = { path = "../datasets" }
