[package]
name = "mei-compiler-tests"
version = "2.0.5"
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
serde_json.workspace = true

[dev-dependencies]
mei-bundle = { path = "../mei-bundle" }
mei-graph = { path = "../mei-graph" }
mei-lang-kernel = { path = "../../../crates/kernel" }
mei-lower = { path = "../mei-lower" }
serde_json.workspace = true
