[package]
name = "mei-compiler-tests"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
serde_json.workspace = true

[dev-dependencies]
mei-bundle = { path = "../mei-bundle" }
mei-graph = { path = "../mei-graph" }
mei-lower = { path = "../mei-lower" }
serde_json.workspace = true
