import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, "..");
const assetsRoot = path.join(root, "app", "assets");
const distRoot = path.join(assetsRoot, "dist");
const vendorRoot = path.resolve(root, "stock", "components", "vendor");
const manifestPath = path.join(__dirname, "bundle-manifest.json");
const rustOutPath = path.join(
  root,
  "server",
  "src",
  "http",
  "pages",
  "bundle_order_generated.rs",
);

function escapeRustStr(s) {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function rustSliceConst(name, arr) {
  const body = arr.map((s) => `    "${escapeRustStr(s)}",`).join("\n");
  return `pub(super) const ${name}: &[&str] = &[\n${body}\n];`;
}

async function loadManifest() {
  const raw = await readFile(manifestPath, "utf8");
  const m = JSON.parse(raw);
  if (
    !Array.isArray(m.manageScripts) ||
    !Array.isArray(m.accessScripts) ||
    !Array.isArray(m.styles)
  ) {
    throw new Error(
      "bundle-manifest.json must contain manageScripts, accessScripts, styles arrays",
    );
  }
  if (!Array.isArray(m.configScripts)) {
    m.configScripts = [];
  }
  if (!Array.isArray(m.uploadScripts)) {
    m.uploadScripts = [];
  }
  if (!Array.isArray(m.manageSourceScripts)) {
    m.manageSourceScripts = [];
  }
  return m;
}

async function writeRustBundleOrder(manifest) {
  const rust = `// AUTO-GENERATED by scripts/build-assets.mjs from scripts/bundle-manifest.json — DO NOT EDIT

${rustSliceConst("BUNDLE_MANAGE_SCRIPTS", manifest.manageScripts)}

${rustSliceConst("BUNDLE_MANAGE_SOURCE_SCRIPTS", manifest.manageSourceScripts)}

${rustSliceConst("BUNDLE_ACCESS_SCRIPTS", manifest.accessScripts)}

${rustSliceConst("BUNDLE_CONFIG_SCRIPTS", manifest.configScripts)}

${rustSliceConst("BUNDLE_UPLOAD_SCRIPTS", manifest.uploadScripts)}

${rustSliceConst("BUNDLE_STYLES_ORDER", manifest.styles)}
`;
  await writeFile(rustOutPath, rust, "utf8");
}

async function concatScripts(outputName, scripts) {
  let content = "// Generated by scripts/build-assets.mjs\n";
  for (const script of scripts) {
    const fullPath = path.join(assetsRoot, script);
    const scriptContent = await readFile(fullPath, "utf8");
    content += `\n/* ===== ${script} ===== */\n`;
    content += scriptContent;
    content += "\n;\n";
  }
  const outputPath = path.join(distRoot, outputName);
  await writeFile(outputPath, content, "utf8");
  return outputPath;
}

async function bundleShoelace() {
  const outputPath = path.join(distRoot, "shoelace.bundle.js");
  await build({
    entryPoints: [path.join(assetsRoot, "shoelace-local.js")],
    outfile: outputPath,
    bundle: true,
    minify: true,
    format: "esm",
    target: "es2020",
    legalComments: "none",
  });
  return outputPath;
}

function stripJsSourceMapReference(js) {
  return String(js || "")
    .replace(/\/\/# sourceMappingURL=.*\r?\n?$/u, "")
    .replace(/\/\*# sourceMappingURL=.*?\*\/\s*$/u, "");
}

async function copyRuntimeVendorAssets() {
  const echartsSrc = path.join(root, "node_modules", "echarts", "dist", "echarts.min.js");
  const maplibreJsSrc = path.join(root, "node_modules", "maplibre-gl", "dist", "maplibre-gl.js");
  const maplibreCssSrc = path.join(root, "node_modules", "maplibre-gl", "dist", "maplibre-gl.css");
  const echartsDstDir = path.join(vendorRoot, "echarts");
  const maplibreDstDir = path.join(vendorRoot, "maplibre");
  await mkdir(echartsDstDir, { recursive: true });
  await mkdir(maplibreDstDir, { recursive: true });
  await copyFile(echartsSrc, path.join(echartsDstDir, "echarts.min.js"));
  const maplibreJs = stripJsSourceMapReference(await readFile(maplibreJsSrc, "utf8"));
  await writeFile(path.join(maplibreDstDir, "maplibre-gl.js"), maplibreJs, "utf8");
  await copyFile(maplibreCssSrc, path.join(maplibreDstDir, "maplibre-gl.css"));
}

async function concatStyles(outputName, styles) {
  let content = "/* Generated by scripts/build-assets.mjs */\n";
  for (const style of styles) {
    const fullPath = path.join(assetsRoot, style);
    const styleContent = await readFile(fullPath, "utf8");
    content += `\n/* ===== ${style} ===== */\n`;
    content += styleContent;
    content += "\n";
  }
  const outputPath = path.join(distRoot, outputName);
  await writeFile(outputPath, content, "utf8");
  return outputPath;
}

async function main() {
  const manifest = await loadManifest();
  await writeRustBundleOrder(manifest);
  await mkdir(distRoot, { recursive: true });
  await copyRuntimeVendorAssets();
  const manageOut = await concatScripts("manage.bundle.js", manifest.manageScripts);
  const manageSourceOut =
    manifest.manageSourceScripts.length > 0
      ? await concatScripts("manage-source.bundle.js", manifest.manageSourceScripts)
      : null;
  const accessOut = await concatScripts("access.bundle.js", manifest.accessScripts);
  const configOut =
    manifest.configScripts.length > 0
      ? await concatScripts("config.bundle.js", manifest.configScripts)
      : null;
  const uploadOut =
    manifest.uploadScripts.length > 0
      ? await concatScripts("upload.bundle.js", manifest.uploadScripts)
      : null;
  const shoelaceOut = await bundleShoelace();
  const stylesOut = await concatStyles("styles.bundle.css", manifest.styles);
  console.log("[assets:build] generated:");
  console.log(`- ${path.relative(root, rustOutPath)}`);
  console.log(`- ${path.relative(root, manageOut)}`);
  if (manageSourceOut) {
    console.log(`- ${path.relative(root, manageSourceOut)}`);
  }
  console.log(`- ${path.relative(root, accessOut)}`);
  if (configOut) {
    console.log(`- ${path.relative(root, configOut)}`);
  }
  if (uploadOut) {
    console.log(`- ${path.relative(root, uploadOut)}`);
  }
  console.log(`- ${path.relative(root, shoelaceOut)}`);
  console.log(`- ${path.relative(root, stylesOut)}`);
  console.log(`- ${path.relative(root, path.join(vendorRoot, "echarts", "echarts.min.js"))}`);
  console.log(`- ${path.relative(root, path.join(vendorRoot, "maplibre", "maplibre-gl.js"))}`);
  console.log(`- ${path.relative(root, path.join(vendorRoot, "maplibre", "maplibre-gl.css"))}`);
}

await main();
