import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, "..");
const assetsRoot = path.join(root, "app", "assets");
const distRoot = path.join(assetsRoot, "dist");

const MANAGE_SCRIPTS = [
  "frame-stage.js",
  "vendor/diff-match-patch.js",
  "vendor/codemirror.js",
  "source-codemirror-mode.js",
  "vendor/codemirror-merge.js",
  "manage-tabs.js",
  "opencode-panel.js",
  "workspace-splitters.js",
  "source-tree-controls.js",
  "source-highlight.js",
  "spa-navigation.js"
];

const ACCESS_SCRIPTS = ["frame-stage.js", "statusbar.js", "spa-navigation.js"];
const STYLES = [
  "app-shell.css",
  "tailwind.css",
  "vendor/codemirror.css",
  "vendor/codemirror-merge.css",
  "vendor/shoelace/themes/dark.css"
];

async function concatScripts(outputName, scripts) {
  let content = "// Generated by scripts/build-assets.mjs\n";
  for (const script of scripts) {
    const fullPath = path.join(assetsRoot, script);
    const scriptContent = await readFile(fullPath, "utf8");
    content += `\n/* ===== ${script} ===== */\n`;
    content += scriptContent;
    content += "\n;\n";
  }
  const outputPath = path.join(distRoot, outputName);
  await writeFile(outputPath, content, "utf8");
  return outputPath;
}

async function bundleShoelace() {
  const outputPath = path.join(distRoot, "shoelace.bundle.js");
  await build({
    entryPoints: [path.join(assetsRoot, "shoelace-local.js")],
    outfile: outputPath,
    bundle: true,
    minify: true,
    format: "esm",
    target: "es2020",
    legalComments: "none"
  });
  return outputPath;
}

async function concatStyles(outputName, styles) {
  let content = "/* Generated by scripts/build-assets.mjs */\n";
  for (const style of styles) {
    const fullPath = path.join(assetsRoot, style);
    const styleContent = await readFile(fullPath, "utf8");
    content += `\n/* ===== ${style} ===== */\n`;
    content += styleContent;
    content += "\n";
  }
  const outputPath = path.join(distRoot, outputName);
  await writeFile(outputPath, content, "utf8");
  return outputPath;
}

async function main() {
  await mkdir(distRoot, { recursive: true });
  const manageOut = await concatScripts("manage.bundle.js", MANAGE_SCRIPTS);
  const accessOut = await concatScripts("access.bundle.js", ACCESS_SCRIPTS);
  const shoelaceOut = await bundleShoelace();
  const stylesOut = await concatStyles("styles.bundle.css", STYLES);
  console.log("[assets:build] generated:");
  console.log(`- ${path.relative(root, manageOut)}`);
  console.log(`- ${path.relative(root, accessOut)}`);
  console.log(`- ${path.relative(root, shoelaceOut)}`);
  console.log(`- ${path.relative(root, stylesOut)}`);
}

await main();
