use super::prelude::*;
use super::*;

pub(crate) fn render_workspace_start_script() -> &'static str {
    r#"#!/usr/bin/env bash
# MeiLang workspace host launcher (generated by `mei-toolchain workspace runtime install`).
set -euo pipefail

DEPLOY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_ROOT="$(cd "${DEPLOY_DIR}/.." && pwd)"
HOST="${MEI_HOST:-127.0.0.1}"
PORT="${MEI_PORT:-9527}"
TOOLCHAIN_MODE="${MEI_TOOLCHAIN_MODE:-cargo}"
MEI_LANG_ROOT="${MEI_LANG_ROOT:-${WORKSPACE_ROOT}/../../mei-lang}"
INSTALLED_HOST_BIN="${WORKSPACE_ROOT}/toolchain/bin/mei-host-web"
LINKS_JSON="${WORKSPACE_ROOT}/deploy/state/links.json"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --toolchain-mode)
      TOOLCHAIN_MODE="$2"
      shift 2
      ;;
    --toolchain-mode=*)
      TOOLCHAIN_MODE="${1#*=}"
      shift
      ;;
    --port)
      PORT="$2"
      shift 2
      ;;
    --port=*)
      PORT="${1#*=}"
      shift
      ;;
    --host)
      HOST="$2"
      shift 2
      ;;
    --host=*)
      HOST="${1#*=}"
      shift
      ;;
    *)
      break
      ;;
  esac
done

URL="http://${HOST}:${PORT}"

echo "MeiLang workspace: ${WORKSPACE_ROOT}"
echo "Toolchain mode: ${TOOLCHAIN_MODE}"
echo "Listen: ${HOST}:${PORT}"
echo "Open: ${URL}"
if [[ -f "${LINKS_JSON}" && "${TOOLCHAIN_MODE}" == "installed" ]]; then
  echo "Links: ${LINKS_JSON} (toolchain.active should match toolchain/MANIFEST.json#version)"
fi
echo ""

if [[ "${TOOLCHAIN_MODE}" == "cargo" ]]; then
  if [[ ! -f "${MEI_LANG_ROOT}/Cargo.toml" ]]; then
    echo "error: MEI_LANG_ROOT=${MEI_LANG_ROOT} is not a mei-lang checkout" >&2
    exit 1
  fi
  echo "cargo mode: incremental compile; stock and prebuild run automatically at startup when needed."
  exec cargo run --manifest-path "${MEI_LANG_ROOT}/Cargo.toml" \
    -p mei-lang-server --bin mei-host-web -- serve \
    --source-root "${WORKSPACE_ROOT}" \
    --toolchain-mode cargo \
    --host "${HOST}" \
    --port "${PORT}" \
    "$@"
fi

if [[ -x "${INSTALLED_HOST_BIN}" ]]; then
  exec "${INSTALLED_HOST_BIN}" serve \
    --source-root "${WORKSPACE_ROOT}" \
    --toolchain-mode installed \
    --host "${HOST}" \
    --port "${PORT}" \
    "$@"
fi

if [[ -n "${MEI_HOST_WEB_BIN:-}" && -x "${MEI_HOST_WEB_BIN}" ]]; then
  exec "${MEI_HOST_WEB_BIN}" serve \
    --source-root "${WORKSPACE_ROOT}" \
    --toolchain-mode installed \
    --host "${HOST}" \
    --port "${PORT}" \
    "$@"
fi

cat >&2 <<EOF
error: cannot find mei-host-web for installed mode.

Try one of:
  1. ./deploy/start.sh --toolchain-mode cargo --port ${PORT}
  2. mei-toolchain workspace runtime install --source-root "${WORKSPACE_ROOT}" --force
  3. export MEI_HOST_WEB_BIN=/path/to/mei-host-web

EOF
exit 1
"#
}

pub(crate) fn render_workspace_prebuild_script() -> &'static str {
    r#"#!/usr/bin/env bash
# MeiLang workspace prebuild launcher (generated by `mei-toolchain workspace runtime install`).
set -euo pipefail

DEPLOY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_ROOT="$(cd "${DEPLOY_DIR}/.." && pwd)"
TOOLCHAIN_MODE="${MEI_TOOLCHAIN_MODE:-cargo}"
MEI_LANG_ROOT="${MEI_LANG_ROOT:-${WORKSPACE_ROOT}/../../mei-lang}"
INSTALLED_TOOLCHAIN_BIN="${WORKSPACE_ROOT}/toolchain/bin/mei-toolchain"
LOCAL_TOOLCHAIN_BIN="${WORKSPACE_ROOT}/.mei/runtime/bin/mei-toolchain"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --toolchain-mode)
      TOOLCHAIN_MODE="$2"
      shift 2
      ;;
    --toolchain-mode=*)
      TOOLCHAIN_MODE="${1#*=}"
      shift
      ;;
    *)
      break
      ;;
  esac
done

echo "MeiLang workspace: ${WORKSPACE_ROOT}"
echo "Toolchain mode: ${TOOLCHAIN_MODE}"
echo ""

run_cargo_prebuild() {
  if [[ ! -f "${MEI_LANG_ROOT}/Cargo.toml" ]]; then
    echo "error: MEI_LANG_ROOT=${MEI_LANG_ROOT} is not a mei-lang checkout" >&2
    exit 1
  fi
  exec cargo run --manifest-path "${MEI_LANG_ROOT}/Cargo.toml" \
    -p mei-lang-server --bin mei-toolchain -- \
    prebuild --source-root "${WORKSPACE_ROOT}" "$@"
}

run_installed_prebuild() {
  local bin=""
  if [[ -x "${LOCAL_TOOLCHAIN_BIN}" ]]; then
    bin="${LOCAL_TOOLCHAIN_BIN}"
  elif [[ -x "${INSTALLED_TOOLCHAIN_BIN}" ]]; then
    bin="${INSTALLED_TOOLCHAIN_BIN}"
  elif [[ -n "${MEI_TOOLCHAIN_BIN:-}" && -x "${MEI_TOOLCHAIN_BIN}" ]]; then
    bin="${MEI_TOOLCHAIN_BIN}"
  elif command -v mei-toolchain >/dev/null 2>&1; then
    bin="$(command -v mei-toolchain)"
  fi
  if [[ -z "${bin}" ]]; then
    cat >&2 <<EOF
error: cannot find mei-toolchain for installed mode.

Try one of:
  1. ./deploy/prebuild.sh --toolchain-mode cargo
  2. mei-toolchain workspace runtime install --source-root "${WORKSPACE_ROOT}" --force
  3. export MEI_TOOLCHAIN_BIN=/path/to/mei-toolchain

EOF
    exit 1
  fi
  exec "${bin}" prebuild --source-root "${WORKSPACE_ROOT}" "$@"
}

if [[ "${TOOLCHAIN_MODE}" == "cargo" ]]; then
  run_cargo_prebuild "$@"
fi

run_installed_prebuild "$@"
"#
}

pub(crate) fn render_workspace_build_promote_script() -> &'static str {
    r#"#!/usr/bin/env bash
# Promote workspace build/store candidate → apps/*/build/active (generated by runtime install).
set -euo pipefail

DEPLOY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_ROOT="$(cd "${DEPLOY_DIR}/.." && pwd)"
TOOLCHAIN_MODE="${MEI_TOOLCHAIN_MODE:-cargo}"
MEI_LANG_ROOT="${MEI_LANG_ROOT:-${WORKSPACE_ROOT}/../../mei-lang}"
INSTALLED_TOOLCHAIN_BIN="${WORKSPACE_ROOT}/toolchain/bin/mei-toolchain"
LOCAL_TOOLCHAIN_BIN="${WORKSPACE_ROOT}/.mei/runtime/bin/mei-toolchain"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --toolchain-mode)
      TOOLCHAIN_MODE="$2"
      shift 2
      ;;
    --toolchain-mode=*)
      TOOLCHAIN_MODE="${1#*=}"
      shift
      ;;
    *)
      break
      ;;
  esac
done

run_cargo_promote() {
  if [[ ! -f "${MEI_LANG_ROOT}/Cargo.toml" ]]; then
    echo "error: MEI_LANG_ROOT=${MEI_LANG_ROOT} is not a mei-lang checkout" >&2
    exit 1
  fi
  exec cargo run --manifest-path "${MEI_LANG_ROOT}/Cargo.toml" \
    -p mei-lang-server --bin mei-toolchain -- \
    workspace build promote --source-root "${WORKSPACE_ROOT}" "$@"
}

run_installed_promote() {
  local bin=""
  if [[ -x "${LOCAL_TOOLCHAIN_BIN}" ]]; then
    bin="${LOCAL_TOOLCHAIN_BIN}"
  elif [[ -x "${INSTALLED_TOOLCHAIN_BIN}" ]]; then
    bin="${INSTALLED_TOOLCHAIN_BIN}"
  elif [[ -n "${MEI_TOOLCHAIN_BIN:-}" && -x "${MEI_TOOLCHAIN_BIN}" ]]; then
    bin="${MEI_TOOLCHAIN_BIN}"
  elif command -v mei-toolchain >/dev/null 2>&1; then
    bin="$(command -v mei-toolchain)"
  fi
  if [[ -z "${bin}" ]]; then
    echo "error: cannot find mei-toolchain; try --toolchain-mode cargo" >&2
    exit 1
  fi
  exec "${bin}" workspace build promote --source-root "${WORKSPACE_ROOT}" "$@"
}

if [[ "${TOOLCHAIN_MODE}" == "cargo" ]]; then
  run_cargo_promote "$@"
fi

run_installed_promote "$@"
"#
}

pub(crate) fn render_common_runtime_json(package_root: &Path) -> Result<String> {
    let mut descriptor = editor_runtime_descriptor_for_package_root(package_root);
    descriptor.package_root = "workspace-local-runtime".to_string();
    descriptor.package_root_resolution = vec![
        "Prefer the workspace-local runtime under `.mei/runtime/bin/`.".to_string(),
        "Use explicit `MEI_TOOLCHAIN_BIN` / `MEI_HOST_WEB_BIN` only as a recovery override."
            .to_string(),
        "A runtime-installed workspace must not require a sibling `mei-lang` checkout.".to_string(),
    ];
    descriptor.standalone_flow = vec![
        "Run `mei-toolchain workspace bootstrap --source-root <dir> [--app <app>] [--tool <tool>] --json` when creating a brand new source workspace.".to_string(),
        "If the source workspace already exists, run `workspace runtime install` or `workspace runtime update` to refresh `.mei/`.".to_string(),
        "If you need the staged flow, run `workspace init`, `workspace runtime install`, then `editor-runtime scaffold`.".to_string(),
        "Use `./deploy/start.sh` to launch the workspace-local `mei-host-web` binary.".to_string(),
        "Use `./deploy/prebuild.sh` to run workspace prebuild without a global `mei-toolchain` on PATH.".to_string(),
        "Use `.mei/runtime/bin/mei-toolchain` and `.mei/runtime/bin/mei-lsp` as the canonical local binaries.".to_string(),
        "Run `mei-toolchain knowledge --surface author --include-content --json` to export packaged authoring docs/examples.".to_string(),
    ];
    serde_json::to_string_pretty(&descriptor).map_err(Into::into)
}

pub(crate) fn render_workspace_runtime_version_json() -> Result<String> {
    serde_json::to_string_pretty(&workspace_runtime_version_descriptor()).map_err(Into::into)
}

pub(crate) fn render_workspace_runtime_manifest_json(package_root: &Path) -> Result<String> {
    serde_json::to_string_pretty(&workspace_runtime_manifest_for_package_root(package_root))
        .map_err(Into::into)
}

pub(crate) fn render_workspace_catalog_json(
    workspace_root: &Path,
    package_root: &Path,
) -> Result<String> {
    serde_json::to_string_pretty(
        &crate::capability_catalog::capability_catalog_descriptor_for_workspace_root(
            workspace_root,
            package_root,
        ),
    )
    .map_err(Into::into)
}

pub(crate) fn render_workspace_surface_json(
    workspace_root: &Path,
    package_root: &Path,
    surface: &str,
) -> Result<String> {
    let descriptor = crate::capability_catalog::mcp_surface_descriptor_for_workspace_root(
        workspace_root,
        package_root,
        surface,
    )
    .ok_or_else(|| anyhow::anyhow!("unsupported mcp surface `{surface}`"))?;
    serde_json::to_string_pretty(&descriptor).map_err(Into::into)
}
